In [2]:
!pip install datasets transformers sentencepiece -q

In [4]:
!pip install torch torchvision torchaudio -q

In [10]:
!pip install "accelerate>=1.1.0" -q

In [9]:
!pip install datasets -q

In [1]:
from datasets import load_dataset

ds = load_dataset("roneneldan/TinyStories", split="train")

print(ds)
print(ds[0])

/home/ubuntu/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Dataset({
    features: ['text'],
    num_rows: 2119719
})
{'text': 'One day, a little girl named Lily found a needle in her room. She knew it was difficult to play with it because it was sharp. Lily wanted to share the needle with her mom, so she could sew a button on her shirt.\n\nLily went to her mom and said, "Mom, I found this needle. Can you share it with me and sew my shirt?" Her mom smiled and said, "Yes, Lily, we can share the needle and fix your shirt."\n\nTogether, they shared the needle and sewed the button on Lily\'s shirt. It was not difficult for them because they were sharing and helping each other. After they finished, Lily thanked her mom for sharing the needle and fixing her shirt. They both felt happy because they had shared and worked together.'}

In [2]:
import numpy as np

lengths = [len(x["text"].split()) for x in ds.select(range(1000))]
print("Avg words:", np.mean(lengths))
print("Max words:", np.max(lengths))

Avg words: 183.801
Max words: 837

In [13]:
# out_path = "tiny_corpus.txt"
# with open(out_path, "w", encoding="utf-8") as f:
#     for ex in ds:
#         txt = ex.get("text", "")
#         if txt:
#             f.write(txt.replace("\r\n", "\n").replace("\r", "\n").strip() + "\n")

# print("Wrote:", out_path)

Wrote: tiny_corpus.txt

In [15]:
# import os
# from tokenizers import ByteLevelBPETokenizer

# tokenizer = ByteLevelBPETokenizer()
# v_size = 8000 # Adjustable

# tokenizer.train(
#     files=["tiny_corpus.txt"],
#     vocab_size=v_size,
#     min_frequency=2,
#     special_tokens=["<s>", "<pad>", "</s>", "<unk>"],
# )

# # Create the target directory in Google Drive if it doesn't exist
# save_directory = "./"
# os.makedirs(save_directory, exist_ok=True)

# # Update file name accordingly to save in the specified drive folder
# tokenizer.save_model(save_directory)
# print(f"Saved to {save_directory}")

Saved to ./

In [3]:
import os

save_directory = "./"

print("Files in directory:")
print(os.listdir(save_directory))

Files in directory:
['.config', '.profile', '.ipynb_checkpoints', 'tokenizer.json', '.nv', '.zshrc', 'runs', 'vocab.json', '.verb-setup.log', '.bash_logout', '.ssh', '.bash_history', 'tiny_corpus.txt', 'TinyStories_SLM (2).ipynb', 'experiment_log.json', 'tinystories_lm_val_512', '.venv', '.cache', '.ipython', '.ollama', 'models.zip', 'tinystories_lm_train_512', 'merges.txt', 'rajs_flow (1).ipynb', '.sudo_as_admin_successful', '.jupyter', 'evaluation.ipynb', '.local', 'gpt_eval_comparison1.json', '.bashrc']

In [17]:
# from tokenizers import ByteLevelBPETokenizer
# import os

# save_directory = "./"
# vocab_path  = os.path.join(save_directory, "vocab.json")
# merges_path = os.path.join(save_directory, "merges.txt")

# bpe = ByteLevelBPETokenizer(vocab_path, merges_path)

# # Save a unified tokenizer file
# bpe.save(os.path.join(save_directory, "tokenizer.json"))
# print("Saved tokenizer.json")

Saved tokenizer.json

In [4]:
from transformers import PreTrainedTokenizerFast
import os

save_directory = "./"

tok = PreTrainedTokenizerFast(
    tokenizer_file=os.path.join(save_directory, "tokenizer.json"),
    bos_token="<s>",
    eos_token="</s>",
    unk_token="<unk>",
    pad_token="<pad>",
)

print("Vocab size:", tok.vocab_size)
print(tok("Once upon a time.")["input_ids"])

Vocab size: 8000
[434, 450, 262, 399, 17]

In [5]:
raw = load_dataset("roneneldan/TinyStories")
train_ds = raw["train"]
val_ds = raw["validation"] if "validation" in raw else train_ds.select(range(2000))

block_size = 512

In [17]:
# def tokenize_fn(batch):
#     out = tok(batch["text"], add_special_tokens=False, return_attention_mask=False)
#     # out only has "input_ids"
#     return out

# tok_train = train_ds.map(tokenize_fn, batched=True, remove_columns=train_ds.column_names)
# tok_val   = val_ds.map(tokenize_fn, batched=True, remove_columns=val_ds.column_names)

# def group_texts(examples):
#     concatenated = []
#     for ids in examples["input_ids"]:
#         concatenated.extend(ids)

#     total_len = (len(concatenated) // block_size) * block_size
#     concatenated = concatenated[:total_len]

#     input_ids = [concatenated[i:i+block_size] for i in range(0, total_len, block_size)]
#     return {"input_ids": input_ids, "labels": input_ids.copy()}

# lm_train = tok_train.map(group_texts, batched=True, remove_columns=tok_train.column_names)
# lm_val   = tok_val.map(group_texts, batched=True, remove_columns=tok_val.column_names)

# print("Packed train blocks:", len(lm_train))
# print("Packed val blocks:", len(lm_val))
# print("One block length:", len(lm_train[0]["input_ids"]))

In [23]:
# lm_train.save_to_disk("./tinystories_lm_train_512")
# lm_val.save_to_disk("./tinystories_lm_val_512")

Saving the dataset (12/12 shards): 100%|██████████| 906933/906933 [00:05<00:00, 179280.39 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 9113/9113 [00:00<00:00, 173588.02 examples/s]

In [6]:
from datasets import load_from_disk

lm_train = load_from_disk("./tinystories_lm_train_512")
lm_val   = load_from_disk("./tinystories_lm_val_512")

print(len(lm_train), len(lm_val))

906933 9113

Hyperparameter Studies

In [22]:
import torch
import torch.nn.functional as F
from transformers import (
    GPT2Config, GPT2LMHeadModel,
    DataCollatorForLanguageModeling,
    TrainingArguments, Trainer
)
import json, os
from lion_pytorch import Lion

# ============ EXPERIMENT CONFIG ============
LEARNING_RATE   = 1e-3          # try: 1e-3, 5e-4, 3e-4, 1e-4
OPTIMIZER_NAME  = "adam"       # try: "adamw", "adam", "sgd"
LABEL_SMOOTHING = 0.2           # try: 0.1, 0.2
RUN_NAME        = "adam_1e-3__ls_0.2_baseline_study"
# ===========================================

data_collator = DataCollatorForLanguageModeling(tok, mlm=False)

config = GPT2Config(
    vocab_size=8000,
    n_positions=512,
    n_ctx=512,
    n_embd=256,
    n_layer=6,
    n_head=8,
    bos_token_id=tok.bos_token_id,
    eos_token_id=tok.eos_token_id,
    pad_token_id=tok.pad_token_id,
)

model = GPT2LMHeadModel(config)
print("Total parameters:", sum(p.numel() for p in model.parameters())/1e6, "M")


# ============ CUSTOM TRAINER ============
class CustomTrainer(Trainer):

    def create_optimizer(self):
        if OPTIMIZER_NAME == "adamw":
            self.optimizer = torch.optim.AdamW(
                self.model.parameters(),
                lr=self.args.learning_rate,
                weight_decay=self.args.weight_decay,
            )
        elif OPTIMIZER_NAME == "adam":
            self.optimizer = torch.optim.Adam(
                self.model.parameters(),
                lr=self.args.learning_rate,
            )
        elif OPTIMIZER_NAME == "sgd":
            self.optimizer = torch.optim.SGD(
                self.model.parameters(),
                lr=self.args.learning_rate,
                momentum=0.9,
                weight_decay=self.args.weight_decay,
            )
        elif OPTIMIZER_NAME == "lion":
            self.optimizer = Lion(
                self.model.parameters(),
                lr=self.args.learning_rate / 3,  # Lion needs ~3x smaller LR than Adam
                weight_decay=self.args.weight_decay,
            )
        return self.optimizer
# ========================================


training_args = TrainingArguments(
    output_dir=f"./runs/{RUN_NAME}",
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    gradient_accumulation_steps=2,
    eval_strategy="steps",
    eval_steps=500,
    logging_steps=100,
    save_steps=1000,
    save_total_limit=2,
    num_train_epochs=1,
    learning_rate=LEARNING_RATE,
    warmup_steps=500,              
    weight_decay=0.1,
    fp16=True,
    report_to="none",
)

trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=lm_train,
    eval_dataset=lm_val,
    data_collator=data_collator,
)

trainer.train()

# ============ LOG RESULTS ============
eval_logs = [x for x in trainer.state.log_history if "eval_loss" in x]

if eval_logs:
    val_loss = eval_logs[-1]["eval_loss"]
    perplexity = torch.exp(torch.tensor(val_loss)).item()

    log_entry = {
        "run_name"        : RUN_NAME,
        "learning_rate"   : LEARNING_RATE,
        "optimizer"       : OPTIMIZER_NAME,
        "label_smoothing" : LABEL_SMOOTHING,
        "final_val_loss"  : val_loss,
        "perplexity"      : perplexity,
    }

    log_path = "./experiment_log.json"
    all_logs = json.load(open(log_path)) if os.path.exists(log_path) else []
    all_logs.append(log_entry)
    json.dump(all_logs, open(log_path, "w"), indent=2)

    print(f"\nRun:        {RUN_NAME}")
    print(f"Val Loss:   {val_loss:.4f}")
    print(f"Perplexity: {perplexity:.2f}")
else:
    print("No eval logs found — check eval_steps vs total training steps")
# =====================================

Total parameters: 6.918144 M

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Run:        adam_1e-3__ls_0.2_baseline_study
Val Loss:   1.6381
Perplexity: 5.15

Baseline Model

In [16]:
import torch
import torch.nn.functional as F
from transformers import (
    GPT2Config, GPT2LMHeadModel,
    DataCollatorForLanguageModeling,
    TrainingArguments, Trainer
)
import json, os
from lion_pytorch import Lion

# ============ EXPERIMENT CONFIG ============
LEARNING_RATE   = 5e-4          # try: 1e-3, 5e-4, 3e-4, 1e-4
OPTIMIZER_NAME  = "adamw"       # try: "adamw", "adam", "sgd"
LABEL_SMOOTHING = 0           # try: 0.0, 0.1, 0.2
RUN_NAME        = "baseline_model"
# ===========================================

data_collator = DataCollatorForLanguageModeling(tok, mlm=False)

config = GPT2Config(
    vocab_size=8000,
    n_positions=512,
    n_ctx=512,
    n_embd=256,
    n_layer=6,
    n_head=8,
    bos_token_id=tok.bos_token_id,
    eos_token_id=tok.eos_token_id,
    pad_token_id=tok.pad_token_id,
)

model = GPT2LMHeadModel(config)
print("Total parameters:", sum(p.numel() for p in model.parameters())/1e6, "M")


# ============ CUSTOM TRAINER ============
class CustomTrainer(Trainer):

    def create_optimizer(self):
        if OPTIMIZER_NAME == "adamw":
            self.optimizer = torch.optim.AdamW(
                self.model.parameters(),
                lr=self.args.learning_rate,
                weight_decay=self.args.weight_decay,
            )
        elif OPTIMIZER_NAME == "adam":
            self.optimizer = torch.optim.Adam(
                self.model.parameters(),
                lr=self.args.learning_rate,
            )
        elif OPTIMIZER_NAME == "sgd":
            self.optimizer = torch.optim.SGD(
                self.model.parameters(),
                lr=self.args.learning_rate,
                momentum=0.9,
                weight_decay=self.args.weight_decay,
            )
        elif OPTIMIZER_NAME == "lion":
            self.optimizer = Lion(
                self.model.parameters(),
                lr=self.args.learning_rate / 3,  # Lion needs ~3x smaller LR than Adam
                weight_decay=self.args.weight_decay,
            )
        return self.optimizer
# ========================================


training_args = TrainingArguments(
    output_dir=f"./runs/{RUN_NAME}",
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    gradient_accumulation_steps=2,
    eval_strategy="steps",
    eval_steps=500,
    logging_steps=100,
    save_steps=1000,
    save_total_limit=2,
    num_train_epochs=1,
    learning_rate=LEARNING_RATE,
    warmup_steps=500,              
    weight_decay=0.1,
    fp16=True,
    report_to="none",
)

trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=lm_train,
    eval_dataset=lm_val,
    data_collator=data_collator,
)

trainer.train()

# Save final model + tokenizer
save_path = f"./runs/{RUN_NAME}/final_model"

trainer.save_model(save_path)   # saves model + trainer config
tok.save_pretrained(save_path)  # saves tokenizer files

print(f"Model saved to: {save_path}")

# ============ LOG RESULTS ============
eval_logs = [x for x in trainer.state.log_history if "eval_loss" in x]

if eval_logs:
    val_loss = eval_logs[-1]["eval_loss"]
    perplexity = torch.exp(torch.tensor(val_loss)).item()

    log_entry = {
        "run_name"        : RUN_NAME,
        "learning_rate"   : LEARNING_RATE,
        "optimizer"       : OPTIMIZER_NAME,
        "label_smoothing" : LABEL_SMOOTHING,
        "final_val_loss"  : val_loss,
        "perplexity"      : perplexity,
    }

    log_path = "./experiment_log.json"
    all_logs = json.load(open(log_path)) if os.path.exists(log_path) else []
    all_logs.append(log_entry)
    json.dump(all_logs, open(log_path, "w"), indent=2)

    print(f"\nRun:        {RUN_NAME}")
    print(f"Val Loss:   {val_loss:.4f}")
    print(f"Perplexity: {perplexity:.2f}")
else:
    print("No eval logs found — check eval_steps vs total training steps")
# =====================================

Total parameters: 6.918144 M

`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 24.66it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 38.50it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 38.55it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 38.59it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 39.02it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 37.68it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 37.51it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 38.40it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 38.32it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 37.62it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 38.57it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 38.06it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 38.52it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 38.02it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 37.71it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 37.53it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 37.17it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 38.24it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 37.51it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 38.02it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 37.52it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 37.98it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 38.25it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 37.44it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 37.67it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 38.01it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 37.57it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 37.87it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 38.78it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 38.57it/s]

Model saved to: ./runs/baseline_model/final_model

Run:        baseline_model
Val Loss:   1.6599
Perplexity: 5.26

Finalised Best Model

In [8]:
import torch
import torch.nn.functional as F
from transformers import (
    GPT2Config, GPT2LMHeadModel,
    DataCollatorForLanguageModeling,
    TrainingArguments, Trainer
)
import json, os
from lion_pytorch import Lion

# ============ EXPERIMENT CONFIG ============
LEARNING_RATE   = 1e-3          # try: 1e-3, 5e-4, 3e-4, 1e-4
OPTIMIZER_NAME  = "adam"       # try: "adamw", "adam", "sgd"
LABEL_SMOOTHING = 0           # try: 0.0, 0.1, 0.2
RUN_NAME        = "finalised_best_model"
# ===========================================

data_collator = DataCollatorForLanguageModeling(tok, mlm=False)

config = GPT2Config(
    vocab_size=8000,
    n_positions=512,
    n_ctx=512,
    n_embd=768,
    n_layer=12,
    n_head=12,
    bos_token_id=tok.bos_token_id,
    eos_token_id=tok.eos_token_id,
    pad_token_id=tok.pad_token_id,
)

model = GPT2LMHeadModel(config)
print("Total parameters:", sum(p.numel() for p in model.parameters())/1e6, "M")


# ============ CUSTOM TRAINER ============
class CustomTrainer(Trainer):

    def create_optimizer(self):
        if OPTIMIZER_NAME == "adamw":
            self.optimizer = torch.optim.AdamW(
                self.model.parameters(),
                lr=self.args.learning_rate,
                weight_decay=self.args.weight_decay,
            )
        elif OPTIMIZER_NAME == "adam":
            self.optimizer = torch.optim.Adam(
                self.model.parameters(),
                lr=self.args.learning_rate,
            )
        elif OPTIMIZER_NAME == "sgd":
            self.optimizer = torch.optim.SGD(
                self.model.parameters(),
                lr=self.args.learning_rate,
                momentum=0.9,
                weight_decay=self.args.weight_decay,
            )
        elif OPTIMIZER_NAME == "lion":
            self.optimizer = Lion(
                self.model.parameters(),
                lr=self.args.learning_rate / 3,  # Lion needs ~3x smaller LR than Adam
                weight_decay=self.args.weight_decay,
            )
        return self.optimizer
# ========================================


training_args = TrainingArguments(
    output_dir=f"./runs/{RUN_NAME}",
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    gradient_accumulation_steps=2,
    eval_strategy="steps",
    eval_steps=500,
    logging_steps=100,
    save_steps=1000,
    save_total_limit=2,
    num_train_epochs=1,
    learning_rate=LEARNING_RATE,
    warmup_steps=500,              
    weight_decay=0.1,
    fp16=True,
    report_to="none",
)

trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=lm_train,
    eval_dataset=lm_val,
    data_collator=data_collator,
)

trainer.train()

# Save final model + tokenizer
save_path = f"./runs/{RUN_NAME}/final_model"

trainer.save_model(save_path)   # saves model + trainer config
tok.save_pretrained(save_path)  # saves tokenizer files

print(f"Model saved to: {save_path}")

# ============ LOG RESULTS ============
eval_logs = [x for x in trainer.state.log_history if "eval_loss" in x]

if eval_logs:
    val_loss = eval_logs[-1]["eval_loss"]
    perplexity = torch.exp(torch.tensor(val_loss)).item()

    log_entry = {
        "run_name"        : RUN_NAME,
        "learning_rate"   : LEARNING_RATE,
        "optimizer"       : OPTIMIZER_NAME,
        "label_smoothing" : LABEL_SMOOTHING,
        "final_val_loss"  : val_loss,
        "perplexity"      : perplexity,
    }

    log_path = "./experiment_log.json"
    all_logs = json.load(open(log_path)) if os.path.exists(log_path) else []
    all_logs.append(log_entry)
    json.dump(all_logs, open(log_path, "w"), indent=2)

    print(f"\nRun:        {RUN_NAME}")
    print(f"Val Loss:   {val_loss:.4f}")
    print(f"Perplexity: {perplexity:.2f}")
else:
    print("No eval logs found — check eval_steps vs total training steps")
# =====================================

Total parameters: 91.593216 M

`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.97it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.05it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.87it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.90it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.93it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.95it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.97it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.10it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.97it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.94it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.95it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.99it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.05it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.02it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.92it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.92it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.91it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.02it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.00it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.09it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.04it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.95it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.87it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.93it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.93it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.92it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.91it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.86it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.93it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.97it/s]

Model saved to: ./runs/finalised_best_model/final_model

Run:        finalised_best_model
Val Loss:   1.2818
Perplexity: 3.60

In [29]:
pip install torch --index-url https://download.pytorch.org/whl/cu124

Looking in indexes: https://download.pytorch.org/whl/cu124
Requirement already satisfied: torch in ./.venv/lib/python3.12/site-packages (2.10.0)
Requirement already satisfied: filelock in ./.venv/lib/python3.12/site-packages (from torch) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in ./.venv/lib/python3.12/site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in ./.venv/lib/python3.12/site-packages (from torch) (82.0.1)
Requirement already satisfied: sympy>=1.13.3 in ./.venv/lib/python3.12/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in ./.venv/lib/python3.12/site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.12/site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in ./.venv/lib/python3.12/site-packages (from torch) (2026.2.0)
Requirement already satisfied: cuda-bindings==12.9.4 in ./.venv/lib/python3.12/site-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in ./.venv/lib/python3.12/site-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in ./.venv/lib/python3.12/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in ./.venv/lib/python3.12/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in ./.venv/lib/python3.12/site-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in ./.venv/lib/python3.12/site-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in ./.venv/lib/python3.12/site-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in ./.venv/lib/python3.12/site-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in ./.venv/lib/python3.12/site-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in ./.venv/lib/python3.12/site-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in ./.venv/lib/python3.12/site-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in ./.venv/lib/python3.12/site-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in ./.venv/lib/python3.12/site-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in ./.venv/lib/python3.12/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in ./.venv/lib/python3.12/site-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in ./.venv/lib/python3.12/site-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in ./.venv/lib/python3.12/site-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in ./.venv/lib/python3.12/site-packages (from cuda-bindings==12.9.4->torch) (1.4.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./.venv/lib/python3.12/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.12/site-packages (from jinja2->torch) (3.0.3)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

Replicating GPTNEO 33M to be trained under 1 epoch

In [9]:
import torch
import torch.nn.functional as F
from transformers import (
    GPTNeoConfig, GPTNeoForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments, Trainer
)
import json, os

# ============ EXPERIMENT CONFIG ============
LEARNING_RATE   = 5e-4
OPTIMIZER_NAME  = "adamw"
LABEL_SMOOTHING = 0.0
RUN_NAME        = "gptneo_33M_replicated"
# ===========================================

data_collator = DataCollatorForLanguageModeling(tok, mlm=False)

# ============ REPLICATED GPT-NEO ARCHITECTURE ============
# Exact config from TinyStories-33M
# Only change: vocab_size 50,257 → 8,000 (your tokenizer)
config = GPTNeoConfig(
    vocab_size              = tok.vocab_size,   # 8,000 ← only change
    hidden_size             = 768,              # same as theirs
    num_layers              = 4,                # same as theirs
    attention_types         = [[["global", "local"], 2]],  # same as theirs
    num_heads               = 16,               # same as theirs
    intermediate_size       = 3072,
    window_size             = 256,              # same as theirs
    max_position_embeddings = 2048,              # changed from 2048 → your context
    embed_dropout           = 0,               # same as theirs
    attention_dropout       = 0,               # same as theirs
    resid_dropout           = 0,               # same as theirs
    layer_norm_epsilon      = 1e-5,            # same as theirs
    initializer_range       = 0.02,            # same as theirs
    bos_token_id            = tok.bos_token_id,
    eos_token_id            = tok.eos_token_id,
)

model = GPTNeoForCausalLM(config)
total_params = sum(p.numel() for p in model.parameters()) / 1e6
print(f"Total parameters: {total_params:.1f}M")
# =========================================================


# ============ CUSTOM TRAINER ============
class CustomTrainer(Trainer):

    def create_optimizer(self):
        if OPTIMIZER_NAME == "adamw":
            self.optimizer = torch.optim.AdamW(
                self.model.parameters(),
                lr=self.args.learning_rate,
                weight_decay=self.args.weight_decay,
            )
        elif OPTIMIZER_NAME == "adam":
            self.optimizer = torch.optim.Adam(
                self.model.parameters(),
                lr=self.args.learning_rate,
            )
        return self.optimizer
# ========================================


# ============ TRAINING ARGUMENTS ============
training_args = TrainingArguments(
    output_dir=f"./runs/{RUN_NAME}",

    # Identical to your other runs
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    gradient_accumulation_steps=2,
    eval_strategy="steps",
    eval_steps=500,
    logging_steps=100,
    save_steps=1000,
    save_total_limit=2,
    num_train_epochs=1,
    fp16=True,
    report_to="none",

    # Standard defaults
    learning_rate=LEARNING_RATE,
    warmup_steps=500,
    weight_decay=0.01,
)

trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=lm_train,
    eval_dataset=lm_val,
    data_collator=data_collator,
)

trainer.train()
# ============================================


# Save model
save_path = f"./runs/{RUN_NAME}/final_model"
trainer.save_model(save_path)
tok.save_pretrained(save_path)
print(f"Model saved to: {save_path}")


# ============ LOG RESULTS ============
eval_logs = [x for x in trainer.state.log_history if "eval_loss" in x]

if eval_logs:
    val_loss   = eval_logs[-1]["eval_loss"]
    perplexity = torch.exp(torch.tensor(val_loss)).item()

    log_entry = {
        "run_name"        : RUN_NAME,
        "learning_rate"   : LEARNING_RATE,
        "optimizer"       : OPTIMIZER_NAME,
        "label_smoothing" : LABEL_SMOOTHING,
        "architecture"    : {
            "model_type"  : "GPT-Neo (replicated TinyStories-33M)",
            "hidden_size" : 768,
            "num_layers"  : 4,
            "num_heads"   : 16,
            "window_size" : 256,
            "vocab"       : tok.vocab_size,
            "params"      : f"{total_params:.1f}M"
        },
        "note"           : "Replicated TinyStories-33M architecture, custom vocab, 1 epoch",
        "final_val_loss" : val_loss,
        "perplexity"     : perplexity,
    }

    log_path  = "./experiment_log.json"
    all_logs  = json.load(open(log_path)) if os.path.exists(log_path) else []
    all_logs.append(log_entry)
    json.dump(all_logs, open(log_path, "w"), indent=2)

    print(f"\n{'='*50}")
    print(f"RESULTS")
    print(f"{'='*50}")
    print(f"Model:      GPT-Neo TinyStories-33M replicated")
    print(f"Params:     {total_params:.1f}M")
    print(f"Val Loss:   {val_loss:.4f}")
    print(f"Perplexity: {perplexity:.2f}")
    print(f"{'='*50}")

    print(f"\nCOMPARISON:")
    print(f"  GPT-Neo replicated: perplexity {perplexity:.2f}")
    print(f"  Your 91.7M ablation: perplexity 3.81")
    if perplexity > 3.81:
        print(f"  → Your 91.7M wins ✅")
    else:
        print(f"  → GPT-Neo replicated wins")
else:
    print("No eval logs found")

Total parameters: 36.1M

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.19it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.73it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.97it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.94it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.88it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  8.00it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.80it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.63it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.91it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.67it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.55it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.50it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.64it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.68it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.60it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.72it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.89it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.66it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.52it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.54it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  7.49it/s]

Model saved to: ./runs/gptneo_33M_replicated/final_model

==================================================
RESULTS
==================================================
Model:      GPT-Neo TinyStories-33M replicated
Params:     36.1M
Val Loss:   1.3924
Perplexity: 4.02
==================================================

COMPARISON:
  GPT-Neo replicated: perplexity 4.02
  Your 91.7M ablation: perplexity 3.81
  → Your 91.7M wins ✅

Evaluation

In [ ]:
import os
os.environ["OPENAI_API_KEY"] = "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"

from openai import OpenAI
client = OpenAI()

In [ ]:
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained("roneneldan/TinyStories-33M")

total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"Total parameters:     {total_params/1e6:.1f}M")
print(f"Trainable parameters: {trainable_params/1e6:.1f}M")
print(f"\nModel config:")
print(model.config)

Baseline vs Best model

In [11]:
import torch
import json
import requests
import yaml
from openai import OpenAI
from transformers import GPT2LMHeadModel, PreTrainedTokenizerFast
from transformers import AutoModelForCausalLM, AutoTokenizer

# ============ LOAD YOUR MODEL ============
your_model_path = "./runs/finalised_best_model/final_model"
your_model = GPT2LMHeadModel.from_pretrained(your_model_path)
your_tok   = PreTrainedTokenizerFast.from_pretrained(your_model_path)
your_model.eval()
print("Your model loaded ✅")

# ============ LOAD BASELINE ============
bl_model_path = "./runs/baseline_model/final_model"
bl_model = GPT2LMHeadModel.from_pretrained(your_model_path)
bl_tok   = PreTrainedTokenizerFast.from_pretrained(your_model_path)
bl_model.eval()
print("Baseline model loaded ✅")

import ollama  # pip install ollama

# ============ OLLAMA EVAL FUNCTION ============
JUDGE_MODEL = "llama3.1:8b"

def gpt_eval(prompt, story, model_name=JUDGE_MODEL):
    eval_prompt = f"""the following exercise, the student is given a beginning of a story. The student needs to complete it into a full story.
    The exercise tests the student's language abilities and creativity. 
    The symbol *** marks the separator between the prescribed beginning and the student's completion: {prompt}***{story}

    Please provide your general assessment about the part written by the student (the one after the *** symbol). Is it grammatically correct? Is it consistent with the beginning of the story? 
    Pay special attention to whether the student manages to complete the sentence which is split in the middle by the separator ***. 

    Now, grade the student's completion in terms of grammar (1-10), creativity (1-10), consistency (1-10), plot (1-10).

    Return ONLY valid JSON and nothing else — no explanation, no markdown, no backticks:
    {{"grammar": 1, "creativity": 1, "consistency": 1, "plot": 1}}"""

    response = ollama.chat(
        model=model_name,
        messages=[{"role": "user", "content": eval_prompt}],
        format="json",
        options={"temperature": 0.0},
    )

    raw = response["message"]["content"]
    raw = raw.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()

    scores = json.loads(raw)

    for key in ["grammar", "creativity", "consistency", "plot"]:
        scores[key] = max(1, min(10, int(scores[key])))

    scores["overall"] = round(
        (scores["grammar"] + scores["creativity"] + scores["consistency"] + scores["plot"]) / 4, 2
    )
    return scores
    
# ============ FETCH OFFICIAL EVALUATION PROMPTS ============
def fetch_official_prompts():
    url = "https://huggingface.co/datasets/roneneldan/TinyStories/resolve/main/Evaluation%20prompts.yaml"
    try:
        response = requests.get(url)
        response.raise_for_status()
        prompts_data = yaml.safe_load(response.text)

        prompts = []
        for item in prompts_data:
            if isinstance(item, dict):
                prompt = item.get("prompt") or item.get("Prompt") or list(item.values())[0]
                prompts.append(prompt)
            elif isinstance(item, str):
                prompts.append(item)

        print(f"Loaded {len(prompts)} official evaluation prompts ✅")
        return prompts

    except Exception as e:
        print(f"Could not fetch official prompts: {e}")
        print("Falling back to manual prompts...")
        return [
            "Once upon a time there was a little girl",
            "One day a puppy named Max went to the park",
            "The princess lived in a big castle",
            "Tom was very sad because he lost his toy",
            "In the forest there lived a friendly dragon",
        ]

prompts = fetch_official_prompts()
prompts = prompts[:50]
print(f"Using {len(prompts)} prompts for evaluation")

# ============ GENERATION FUNCTION ============
def generate_story(model, tokenizer, prompt, max_new_tokens=200):
    inputs = tokenizer(prompt, return_tensors="pt")
    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=1.0,
            top_p=0.95,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
        )
    full_text = tokenizer.decode(output[0], skip_special_tokens=True)
    generated = full_text[len(prompt):].strip()
    return generated

# ============ EVALUATE ONE MODEL ============
def evaluate_model(model, tokenizer, model_label, prompts, n_completions=10, judge_model="llama3.1:8b"):
    print(f"\n{'='*60}")
    print(f"Evaluating {model_label}...")
    print(f"{'='*60}")

    all_grammar     = []
    all_creativity  = []
    all_consistency = []
    all_plot = []
    all_overall     = []
    results         = []

    for i, prompt in enumerate(prompts):
        print(f"\nPrompt {i+1}/{len(prompts)}: '{prompt}'")

        prompt_grammar     = []
        prompt_creativity  = []
        prompt_consistency = []
        prompt_plot = []
        prompt_stories = []

        for j in range(n_completions):
            story  = generate_story(model, tokenizer, prompt)
            scores = gpt_eval(prompt, story, model_name=judge_model)

            prompt_grammar.append(scores["grammar"])
            prompt_creativity.append(scores["creativity"])
            prompt_consistency.append(scores["consistency"])
            prompt_plot.append(scores["plot"])
            prompt_stories.append(story)

            print(
                f"  [{j+1}/{n_completions}] "
                f"grammar={scores['grammar']} "
                f"creativity={scores['creativity']} "
                f"consistency={scores['consistency']} "
                f"plot={scores['plot']} "
                f"overall={scores['overall']}"
            )

        avg_grammar     = round(sum(prompt_grammar)     / n_completions, 2)
        avg_creativity  = round(sum(prompt_creativity)  / n_completions, 2)
        avg_consistency = round(sum(prompt_consistency) / n_completions, 2)
        avg_plot = round(sum(prompt_plot) / n_completions, 2)
        avg_overall     = round((avg_grammar + avg_creativity + avg_consistency + avg_plot) / 4, 2)

        all_grammar.append(avg_grammar)
        all_creativity.append(avg_creativity)
        all_consistency.append(avg_consistency)
        all_plot.append(avg_plot)
        all_overall.append(avg_overall)

        results.append({
            "prompt"          : prompt,
            "stories"         : prompt_stories,
            "avg_grammar"     : avg_grammar,
            "avg_creativity"  : avg_creativity,
            "avg_consistency" : avg_consistency,
            "avg_plot"        : avg_plot,
            "avg_overall"     : avg_overall,
        })

        print(
            f"  → Prompt average: "
            f"grammar={avg_grammar} "
            f"creativity={avg_creativity} "
            f"consistency={avg_consistency} "
            f"plot={avg_plot} "
            f"overall={avg_overall}"
        )

    final = {
        "model"       : model_label,
        "grammar"     : round(sum(all_grammar)     / len(prompts), 2),
        "creativity"  : round(sum(all_creativity)  / len(prompts), 2),
        "consistency" : round(sum(all_consistency) / len(prompts), 2),
        "plot"        : round(sum(all_plot)        / len(prompts), 2),
        "overall"     : round(sum(all_overall)     / len(prompts), 2),
        "per_prompt"  : results,
    }

    return final

# ============ RUN EVALUATION ============
N_COMPLETIONS = 10
JUDGE_MODEL = "llama3.1:8b"

your_results = evaluate_model(
    your_model, your_tok,
    "Your Model (91.5M GPT-2, ablation params)",
    prompts,
    n_completions=N_COMPLETIONS,
    judge_model=JUDGE_MODEL
)

baseline_results = evaluate_model(
    bl_model, bl_tok,
    "Baseline Model (7M)",
    prompts,
    n_completions=N_COMPLETIONS,
    judge_model=JUDGE_MODEL
)

# ============ SAVE RESULTS ============
all_results = {
    "evaluation_config": {
        "n_prompts"     : len(prompts),
        "n_completions" : N_COMPLETIONS,
        "total_stories" : len(prompts) * N_COMPLETIONS * 2,
        "evaluator"     : JUDGE_MODEL,
        "methodology"   : "LLM-as-a-judge replicating TinyStories GPT-eval framework",
        "comparison"    : "Equal training budget (1 epoch each)"
    },
    "your_model" : your_results,
    "baseline_7m"    : baseline_results,
}

with open("./gpt_eval_comparison1.json", "w") as f:
    json.dump(all_results, f, indent=2)

print("\nResults saved to gpt_eval_comparison1.json ✅")

# ============ PRINT FINAL COMPARISON ============
print(f"\n{'='*65}")
print("COMPARISON 1 — EQUAL TRAINING BUDGET")
print("Your 91.7M (ablation) vs Baseline Model (7M)")
print(f"{len(prompts)} prompts × {N_COMPLETIONS} completions = "
      f"{len(prompts)*N_COMPLETIONS} stories per model")
print(f"{'='*65}")

print(f"\n{'Metric':<15} {'Your 91.7M':>15} {'Baseline Model 7M':>15} {'Winner':>10}")
print(f"{'─'*57}")

your_wins = 0
baseline_wins  = 0

for metric in ["grammar", "creativity", "consistency", "plot", "overall"]:
    your_val = your_results[metric]
    baseline_val  = baseline_results[metric]

    if your_val >= baseline_val:
        winner = "YOURS ✅"
        your_wins += 1
    else:
        winner = "BASELINE ✅"
        baseline_wins += 1

    print(f"{metric:<15} {str(your_val):>15} {str(baseline_val):>15} {winner:>10}")

print(f"{'─'*57}")
print(f"{'Total wins':<15} {str(your_wins):>15} {str(baseline_wins):>15}")
print(f"\n{'='*65}")
print(f"Context:")
print(f"  Your model:    91.7M params, GPT-2 arch, ablation hyperparams")
print(f"  Baseline Model:   7M params, GPT-2 arch, standard hyperparams")
print(f"  Both trained:  1 epoch on TinyStories")
print(f"{'='*65}")

Loading weights: 100%|██████████| 148/148 [00:00<00:00, 11995.30it/s]

Your model loaded ✅

Loading weights: 100%|██████████| 148/148 [00:00<00:00, 10778.53it/s]

Baseline model loaded ✅
Loaded 44 official evaluation prompts ✅
Using 44 prompts for evaluation

============================================================
Evaluating Your Model (91.5M GPT-2, ablation params)...
============================================================

Prompt 1/44: 'Once upon a time, there lived a bunny in a field. Her name was Lucy. Lucy loved to have feasts and parties with her bunny friends. One day, when Lucy was about to leave for a feast at a friend's house, she realized she's starting to feel sick. She was so weak she could'
  [1/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=4 creativity=2 consistency=3 plot=5 overall=3.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=4.8 creativity=3.7 consistency=4.7 plot=4.1 overall=4.32

Prompt 2/44: 'One day a girl walked into the living room and noticed something very strange. There was a huge cabinet standing in the corner. It looked very old and heavy. She walked over and tried to open it, when suddenly'
  [1/10] grammar=2 creativity=6 consistency=4 plot=5 overall=4.25
  [2/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=4 creativity=6 consistency=5 plot=7 overall=5.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=4.8 creativity=4.4 consistency=5.1 plot=4.4 overall=4.67

Prompt 3/44: 'Once upon a time, there lived a hamster in the forest. Every day, he would walked around the forest and looking for adventures. One day, he heard someone calling out from behind the bushes.

The hamster listened carefully. He realised that it was a small mouse calling out for help. It got stuck under a heavy log and couldn't get out. The hamster immediately realized that'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [9/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=6.2 creativity=4.5 consistency=6.1 plot=4.4 overall=5.3

Prompt 4/44: 'Jack asked his mom if he could ride the bike all the way to his grandmother's house. She agreed, but she said that he shouldn't ride too fast because it was raining and the path was wet.

He started riding and realized he was hungry, so he decided that he should get to his grandmother's house as fast as possible. But then he remembered his mum's words "'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=2 creativity=6 consistency=4 plot=5 overall=4.25
  [3/10] grammar=4 creativity=3 consistency=2 plot=5 overall=3.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=2 creativity=6 consistency=4 plot=5 overall=4.25
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=2 creativity=6 consistency=4 plot=5 overall=4.25
  → Prompt average: grammar=3.4 creativity=4.2 consistency=3.9 plot=4.3 overall=3.95

Prompt 5/44: 'Alice was bored and wanted to find some adventures. She walked up to her friend Ben, who looked vey busy playing with his toys. Alice said, "Why don't we'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=4.8 creativity=3.7 consistency=4.7 plot=3.6 overall=4.2

Prompt 6/44: 'Alice walked up to her friend Ben's house. She was planning to ask him to go to the park with her. When Ben opened the door, she asked him if he had any plans. He said, "I'm sorry, Alice, but'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=4.6 creativity=4.1 consistency=5.4 plot=4.4 overall=4.62

Prompt 7/44: 'The day before Ben's birthday, Alice walked into the kitchen and saw Ben sitting there, looking Gloomy. She said, "Ben, why are you'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [3/10] grammar=2 creativity=6 consistency=8 plot=4 overall=5.0
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  → Prompt average: grammar=5.0 creativity=4.5 consistency=6.2 plot=4.9 overall=5.15

Prompt 8/44: 'Alice walked into the kitchen and saw Ben who was looking for something but looked frustrated. She said, "Ben, why are you'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [3/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [6/10] grammar=8 creativity=2 consistency=6 plot=4 overall=5.0
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=5.4 creativity=3.9 consistency=5.6 plot=4.5 overall=4.85

Prompt 9/44: 'Once upon a time there was a curious boy who lived in a house with a big garden. Every day he explored the garden he found new surprises. But one day, it was raining so hard that his mother told him'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [6/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=4 creativity=2 consistency=3 plot=5 overall=3.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=5.2 creativity=4.1 consistency=5.4 plot=4.2 overall=4.73

Prompt 10/44: 'Once upon a time, there was tiger who liked to play the guitar. One day, a bunny heard the guitar from a distance and'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [5/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [6/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [7/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [8/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=6.4 creativity=4.7 consistency=6.3 plot=4.7 overall=5.53

Prompt 11/44: 'Alice wanted to play with her doll, but she couldn't remember where she had put it. She looked all around the house but couldn't find it, so she decided'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=8 creativity=2 consistency=6 plot=4 overall=5.0
  [10/10] grammar=4 creativity=6 consistency=3 plot=5 overall=4.5
  → Prompt average: grammar=5.0 creativity=3.9 consistency=4.8 plot=4.2 overall=4.47

Prompt 12/44: '"Ben, what do you have in your pocket?", Alice asked. "Oh, nothing.", Ben replied. But Alice saw that there was definitely something in Ben's pocket, and she was very curious what it was, so she'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=4 creativity=6 consistency=5 plot=7 overall=5.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=4.6 creativity=3.9 consistency=4.7 plot=4.0 overall=4.3

Prompt 13/44: 'One day, a bird was flying high over the sea. At some point the bird noticed small boat with a boy sitting inside. The boy looked lost so'
  [1/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=2 creativity=6 consistency=8 plot=4 overall=5.0
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  → Prompt average: grammar=4.6 creativity=4.4 consistency=5.8 plot=4.3 overall=4.78

Prompt 14/44: 'Jimmy was on his way to school with his father when he noticed a tree with strange looking fruits on it. He asked his father, "Can I try'
  [1/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=8 creativity=6 consistency=9 plot=5 overall=7.0
  [4/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=6 creativity=4 consistency=8 plot=5 overall=5.75
  → Prompt average: grammar=5.0 creativity=4.2 consistency=5.9 plot=4.9 overall=5.0

Prompt 15/44: 'Once upon a time, there lived two best friends called Jack and Joe. They were bored, they wanted someone else to talk to or play with. Jack had an idea. He said to Joe, “Let’s go and find'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=8 creativity=2 consistency=6 plot=4 overall=5.0
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=2 creativity=3 consistency=8 plot=6 overall=4.75
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=4.0 creativity=3.4 consistency=5.3 plot=4.8 overall=4.38

Prompt 16/44: 'Jack and Sally were running through the woods together when they stopped suddenly. They heard a strange sound coming from around the corner.

“What's that?” asked Jack.

Sally put her finger to her lips and said, “Shhhh. Let's go find out.”

Jack and Sally followed the'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=4 creativity=6 consistency=8 plot=7 overall=6.25
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=3.0 creativity=3.5 consistency=4.4 plot=4.7 overall=3.9

Prompt 17/44: 'Once upon a time there was a little bear named Diva. She was hungry, and wanted to bake a cake, but she didn't have any sugar at home, so she decided to go ask around. She started walking and met a squirrel. She asked the squirrel, "Would you happen'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=2 creativity=6 consistency=8 plot=9 overall=6.25
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [8/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [9/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=5.4 creativity=4.6 consistency=6.3 plot=5.2 overall=5.38

Prompt 18/44: 'Anna was a popular girl, who walked to school every day carrying a very heavy backpack. It was so heavy that she could hardly walk.

One day, Anna's friends asked her why her backpack was so heavy. She said that'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=2.4 creativity=3.4 consistency=4.5 plot=5.0 overall=3.83

Prompt 19/44: 'Once there was a young girl named Anna. She was three years old and usually very happy. Today she was sad because she couldn't play in the park. She had asked her parents to take her but they wouldn't listen. Anna insisted that '
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [8/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=6.0 creativity=4.6 consistency=6.4 plot=5.0 overall=5.5

Prompt 20/44: 'One day, Grandma was in the kitchen getting ready to prepare. She had the ingredients for a tasty dish.

Grandma said to her granddaughter, "Are you going to help me make this meal?" Her granddaughter, Jenny, replied, "Yes, I will help you!"

Grandma and Jenny began to prepare the ingredients. Jenny was clumsy. She dropped'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=4.4 creativity=3.9 consistency=5.0 plot=4.0 overall=4.33

Prompt 21/44: 'Once upon a time there was a boy named Max. He was at the market with his mother, where he saw two things he wanted very much: a toy car and a jumping rope.

He knew that his mother would not let him buy both of these things, and that she would probably tell him that he has to choose one. He said to her, "I want both'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5

Best model vs Tiny Stories open source model

In [8]:
import torch
import json
import requests
import yaml
from openai import OpenAI
from transformers import GPT2LMHeadModel, PreTrainedTokenizerFast
from transformers import AutoModelForCausalLM, AutoTokenizer

# ============ LOAD YOUR MODEL ============
your_model_path = "./runs/finalised_best_model/final_model"
your_model = GPT2LMHeadModel.from_pretrained(your_model_path)
your_tok   = PreTrainedTokenizerFast.from_pretrained(your_model_path)
your_model.eval()
print("Your model loaded ✅")

# ============ LOAD TINYSTORIES-33M ============
ts_model = AutoModelForCausalLM.from_pretrained("roneneldan/TinyStories-33M")
ts_tok   = AutoTokenizer.from_pretrained("EleutherAI/gpt-neo-125M")
ts_tok.pad_token = ts_tok.eos_token
ts_model.eval()
print("TinyStories-33M loaded ✅")

import ollama  # pip install ollama

# ============ OLLAMA EVAL FUNCTION ============
JUDGE_MODEL = "llama3.1:8b"

def gpt_eval(prompt, story, model_name=JUDGE_MODEL):
    eval_prompt = f"""the following exercise, the student is given a beginning of a story. The student needs to complete it into a full story.
    The exercise tests the student's language abilities and creativity. 
    The symbol *** marks the separator between the prescribed beginning and the student's completion: {prompt}***{story}

    Please provide your general assessment about the part written by the student (the one after the *** symbol). Is it grammatically correct? Is it consistent with the beginning of the story? 
    Pay special attention to whether the student manages to complete the sentence which is split in the middle by the separator ***. 

    Now, grade the student's completion in terms of grammar (1-10), creativity (1-10), consistency (1-10), plot (1-10).

    Return ONLY valid JSON and nothing else — no explanation, no markdown, no backticks:
    {{"grammar": 1, "creativity": 1, "consistency": 1, "plot": 1}}"""

    response = ollama.chat(
        model=model_name,
        messages=[{"role": "user", "content": eval_prompt}],
        format="json",
        options={"temperature": 0.0},
    )

    raw = response["message"]["content"]
    raw = raw.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()

    scores = json.loads(raw)

    for key in ["grammar", "creativity", "consistency", "plot"]:
        scores[key] = max(1, min(10, int(scores[key])))

    scores["overall"] = round(
        (scores["grammar"] + scores["creativity"] + scores["consistency"] + scores["plot"]) / 4, 2
    )
    return scores
    
# ============ FETCH OFFICIAL EVALUATION PROMPTS ============
def fetch_official_prompts():
    url = "https://huggingface.co/datasets/roneneldan/TinyStories/resolve/main/Evaluation%20prompts.yaml"
    try:
        response = requests.get(url)
        response.raise_for_status()
        prompts_data = yaml.safe_load(response.text)

        prompts = []
        for item in prompts_data:
            if isinstance(item, dict):
                prompt = item.get("prompt") or item.get("Prompt") or list(item.values())[0]
                prompts.append(prompt)
            elif isinstance(item, str):
                prompts.append(item)

        print(f"Loaded {len(prompts)} official evaluation prompts ✅")
        return prompts

    except Exception as e:
        print(f"Could not fetch official prompts: {e}")
        print("Falling back to manual prompts...")
        return [
            "Once upon a time there was a little girl",
            "One day a puppy named Max went to the park",
            "The princess lived in a big castle",
            "Tom was very sad because he lost his toy",
            "In the forest there lived a friendly dragon",
        ]

prompts = fetch_official_prompts()
prompts = prompts[:50]
print(f"Using {len(prompts)} prompts for evaluation")

# ============ GENERATION FUNCTION ============
def generate_story(model, tokenizer, prompt, max_new_tokens=200):
    inputs = tokenizer(prompt, return_tensors="pt")
    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=1.0,
            top_p=0.95,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
        )
    full_text = tokenizer.decode(output[0], skip_special_tokens=True)
    generated = full_text[len(prompt):].strip()
    return generated

# ============ EVALUATE ONE MODEL ============
def evaluate_model(model, tokenizer, model_label, prompts, n_completions=10, judge_model="llama3.1:8b"):
    print(f"\n{'='*60}")
    print(f"Evaluating {model_label}...")
    print(f"{'='*60}")

    all_grammar     = []
    all_creativity  = []
    all_consistency = []
    all_plot = []
    all_overall     = []
    results         = []

    for i, prompt in enumerate(prompts):
        print(f"\nPrompt {i+1}/{len(prompts)}: '{prompt}'")

        prompt_grammar     = []
        prompt_creativity  = []
        prompt_consistency = []
        prompt_plot = []
        prompt_stories = []

        for j in range(n_completions):
            story  = generate_story(model, tokenizer, prompt)
            scores = gpt_eval(prompt, story, model_name=judge_model)

            prompt_grammar.append(scores["grammar"])
            prompt_creativity.append(scores["creativity"])
            prompt_consistency.append(scores["consistency"])
            prompt_plot.append(scores["plot"])
            prompt_stories.append(story)

            print(
                f"  [{j+1}/{n_completions}] "
                f"grammar={scores['grammar']} "
                f"creativity={scores['creativity']} "
                f"consistency={scores['consistency']} "
                f"plot={scores['plot']} "
                f"overall={scores['overall']}"
            )

        avg_grammar     = round(sum(prompt_grammar)     / n_completions, 2)
        avg_creativity  = round(sum(prompt_creativity)  / n_completions, 2)
        avg_consistency = round(sum(prompt_consistency) / n_completions, 2)
        avg_plot = round(sum(prompt_plot) / n_completions, 2)
        avg_overall     = round((avg_grammar + avg_creativity + avg_consistency + avg_plot) / 4, 2)

        all_grammar.append(avg_grammar)
        all_creativity.append(avg_creativity)
        all_consistency.append(avg_consistency)
        all_plot.append(avg_plot)
        all_overall.append(avg_overall)

        results.append({
            "prompt"          : prompt,
            "stories"         : prompt_stories,
            "avg_grammar"     : avg_grammar,
            "avg_creativity"  : avg_creativity,
            "avg_consistency" : avg_consistency,
            "avg_plot"        : avg_plot,
            "avg_overall"     : avg_overall,
        })

        print(
            f"  → Prompt average: "
            f"grammar={avg_grammar} "
            f"creativity={avg_creativity} "
            f"consistency={avg_consistency} "
            f"plot={avg_plot} "
            f"overall={avg_overall}"
        )

    final = {
        "model"       : model_label,
        "grammar"     : round(sum(all_grammar)     / len(prompts), 2),
        "creativity"  : round(sum(all_creativity)  / len(prompts), 2),
        "consistency" : round(sum(all_consistency) / len(prompts), 2),
        "plot"        : round(sum(all_plot)        / len(prompts), 2),
        "overall"     : round(sum(all_overall)     / len(prompts), 2),
        "per_prompt"  : results,
    }

    return final

# ============ RUN EVALUATION ============
N_COMPLETIONS = 10
JUDGE_MODEL = "llama3.1:8b"

your_results = evaluate_model(
    your_model, your_tok,
    "Your Model (91.5M GPT-2, ablation params)",
    prompts,
    n_completions=N_COMPLETIONS,
    judge_model=JUDGE_MODEL
)

neo_results = evaluate_model(
    ts_model, ts_tok,
    "GPT-Neo 33M (Open Source Model)",
    prompts,
    n_completions=N_COMPLETIONS,
    judge_model=JUDGE_MODEL
)

# ============ SAVE RESULTS ============
all_results = {
    "evaluation_config": {
        "n_prompts"     : len(prompts),
        "n_completions" : N_COMPLETIONS,
        "total_stories" : len(prompts) * N_COMPLETIONS * 2,
        "evaluator"     : JUDGE_MODEL,
        "methodology"   : "LLM-as-a-judge replicating TinyStories GPT-eval framework",
        "comparison"    : "Equal training budget (1 epoch each)"
    },
    "your_model" : your_results,
    "neo_33m"    : neo_results,
}

with open("./gpt_eval_comparison1.json", "w") as f:
    json.dump(all_results, f, indent=2)

print("\nResults saved to gpt_eval_comparison1.json ✅")

# ============ PRINT FINAL COMPARISON ============
print(f"\n{'='*65}")
print("COMPARISON 1 — EQUAL TRAINING BUDGET")
print("Your 91.7M (ablation) vs GPT-Neo 33M (Open Source)")
print(f"{len(prompts)} prompts × {N_COMPLETIONS} completions = "
      f"{len(prompts)*N_COMPLETIONS} stories per model")
print(f"{'='*65}")

print(f"\n{'Metric':<15} {'Your 91.7M':>15} {'GPT-Neo 33M':>15} {'Winner':>10}")
print(f"{'─'*57}")

your_wins = 0
neo_wins  = 0

for metric in ["grammar", "creativity", "consistency", "plot", "overall"]:
    your_val = your_results[metric]
    neo_val  = neo_results[metric]

    if your_val >= neo_val:
        winner = "YOURS ✅"
        your_wins += 1
    else:
        winner = "NEO ✅"
        neo_wins += 1

    print(f"{metric:<15} {str(your_val):>15} {str(neo_val):>15} {winner:>10}")

print(f"{'─'*57}")
print(f"{'Total wins':<15} {str(your_wins):>15} {str(neo_wins):>15}")
print(f"\n{'='*65}")
print(f"Context:")
print(f"  Your model:    91.7M params, GPT-2 arch, ablation hyperparams")
print(f"  GPT-Neo 33M:   31.1M params, GPT-Neo arch, standard hyperparams")
print(f"  Both trained:  1 epoch on TinyStories")
print(f"{'='*65}")

Loading weights: 100%|██████████| 148/148 [00:00<00:00, 10639.06it/s]

Your model loaded ✅

Loading weights: 100%|██████████| 56/56 [00:00<00:00, 67281.87it/s]
GPTNeoForCausalLM LOAD REPORT from: roneneldan/TinyStories-33M
Key                                                   | Status     |  |
------------------------------------------------------+------------+--+-
transformer.h.{0, 1, 2, 3}.attn.attention.masked_bias | UNEXPECTED |  |
transformer.h.{0, 1, 2, 3}.attn.attention.bias        | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

TinyStories-33M loaded ✅
Loaded 44 official evaluation prompts ✅
Using 44 prompts for evaluation

============================================================
Evaluating Your Model (91.5M GPT-2, ablation params)...
============================================================

Prompt 1/44: 'Once upon a time, there lived a bunny in a field. Her name was Lucy. Lucy loved to have feasts and parties with her bunny friends. One day, when Lucy was about to leave for a feast at a friend's house, she realized she's starting to feel sick. She was so weak she could'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  → Prompt average: grammar=4.8 creativity=4.3 consistency=5.8 plot=4.8 overall=4.92

Prompt 2/44: 'One day a girl walked into the living room and noticed something very strange. There was a huge cabinet standing in the corner. It looked very old and heavy. She walked over and tried to open it, when suddenly'
  [1/10] grammar=2 creativity=6 consistency=8 plot=4 overall=5.0
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=5.0 creativity=4.2 consistency=5.1 plot=3.7 overall=4.5

Prompt 3/44: 'Once upon a time, there lived a hamster in the forest. Every day, he would walked around the forest and looking for adventures. One day, he heard someone calling out from behind the bushes.

The hamster listened carefully. He realised that it was a small mouse calling out for help. It got stuck under a heavy log and couldn't get out. The hamster immediately realized that'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  → Prompt average: grammar=5.8 creativity=4.4 consistency=6.0 plot=4.6 overall=5.2

Prompt 4/44: 'Jack asked his mom if he could ride the bike all the way to his grandmother's house. She agreed, but she said that he shouldn't ride too fast because it was raining and the path was wet.

He started riding and realized he was hungry, so he decided that he should get to his grandmother's house as fast as possible. But then he remembered his mum's words "'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=6 creativity=4 consistency=3 plot=5 overall=4.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=2 creativity=6 consistency=8 plot=4 overall=5.0
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=4 creativity=6 consistency=5 plot=7 overall=5.5
  → Prompt average: grammar=3.8 creativity=4.0 consistency=4.7 plot=4.5 overall=4.25

Prompt 5/44: 'Alice was bored and wanted to find some adventures. She walked up to her friend Ben, who looked vey busy playing with his toys. Alice said, "Why don't we'
  [1/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [2/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=2 creativity=3 consistency=8 plot=6 overall=4.75
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=6 creativity=4 consistency=7 plot=5 overall=5.5
  [10/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  → Prompt average: grammar=5.8 creativity=4.4 consistency=6.4 plot=4.8 overall=5.35

Prompt 6/44: 'Alice walked up to her friend Ben's house. She was planning to ask him to go to the park with her. When Ben opened the door, she asked him if he had any plans. He said, "I'm sorry, Alice, but'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=2 creativity=6 consistency=8 plot=9 overall=6.25
  [6/10] grammar=8 creativity=6 consistency=9 plot=5 overall=7.0
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=2 creativity=6 consistency=8 plot=9 overall=6.25
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=4.0 creativity=4.4 consistency=6.0 plot=5.6 overall=5.0

Prompt 7/44: 'The day before Ben's birthday, Alice walked into the kitchen and saw Ben sitting there, looking Gloomy. She said, "Ben, why are you'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=8 creativity=6 consistency=9 plot=5 overall=7.0
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=8 creativity=6 consistency=9 plot=5 overall=7.0
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=3.6 creativity=3.7 consistency=5.1 plot=4.8 overall=4.3

Prompt 8/44: 'Alice walked into the kitchen and saw Ben who was looking for something but looked frustrated. She said, "Ben, why are you'
  [1/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=8 creativity=2 consistency=6 plot=4 overall=5.0
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [6/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  → Prompt average: grammar=6.6 creativity=4.5 consistency=6.6 plot=4.9 overall=5.65

Prompt 9/44: 'Once upon a time there was a curious boy who lived in a house with a big garden. Every day he explored the garden he found new surprises. But one day, it was raining so hard that his mother told him'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [6/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=5.8 creativity=4.4 consistency=6.0 plot=4.6 overall=5.2

Prompt 10/44: 'Once upon a time, there was tiger who liked to play the guitar. One day, a bunny heard the guitar from a distance and'
  [1/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [2/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [3/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [10/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  → Prompt average: grammar=6.6 creativity=5.2 consistency=7.3 plot=5.4 overall=6.12

Prompt 11/44: 'Alice wanted to play with her doll, but she couldn't remember where she had put it. She looked all around the house but couldn't find it, so she decided'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=8 creativity=6 consistency=5 plot=4 overall=5.75
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=5.4 creativity=4.3 consistency=5.5 plot=4.5 overall=4.92

Prompt 12/44: '"Ben, what do you have in your pocket?", Alice asked. "Oh, nothing.", Ben replied. But Alice saw that there was definitely something in Ben's pocket, and she was very curious what it was, so she'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=5.0 creativity=3.9 consistency=5.1 plot=4.0 overall=4.5

Prompt 13/44: 'One day, a bird was flying high over the sea. At some point the bird noticed small boat with a boy sitting inside. The boy looked lost so'
  [1/10] grammar=2 creativity=3 consistency=8 plot=6 overall=4.75
  [2/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [3/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=2 creativity=6 consistency=8 plot=4 overall=5.0
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=2 creativity=6 consistency=8 plot=4 overall=5.0
  [10/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  → Prompt average: grammar=4.0 creativity=4.7 consistency=6.8 plot=5.1 overall=5.15

Prompt 14/44: 'Jimmy was on his way to school with his father when he noticed a tree with strange looking fruits on it. He asked his father, "Can I try'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=3.8 creativity=3.6 consistency=4.4 plot=4.4 overall=4.05

Prompt 15/44: 'Once upon a time, there lived two best friends called Jack and Joe. They were bored, they wanted someone else to talk to or play with. Jack had an idea. He said to Joe, “Let’s go and find'
  [1/10] grammar=2 creativity=6 consistency=8 plot=4 overall=5.0
  [2/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [6/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [7/10] grammar=6 creativity=4 consistency=7 plot=5 overall=5.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  → Prompt average: grammar=5.4 creativity=4.6 consistency=6.3 plot=4.8 overall=5.28

Prompt 16/44: 'Jack and Sally were running through the woods together when they stopped suddenly. They heard a strange sound coming from around the corner.

“What's that?” asked Jack.

Sally put her finger to her lips and said, “Shhhh. Let's go find out.”

Jack and Sally followed the'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [3/10] grammar=2 creativity=6 consistency=8 plot=4 overall=5.0
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=2 creativity=3 consistency=8 plot=6 overall=4.75
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=2 creativity=6 consistency=4 plot=5 overall=4.25
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=2.0 creativity=3.6 consistency=4.8 plot=5.0 overall=3.85

Prompt 17/44: 'Once upon a time there was a little bear named Diva. She was hungry, and wanted to bake a cake, but she didn't have any sugar at home, so she decided to go ask around. She started walking and met a squirrel. She asked the squirrel, "Would you happen'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [10/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  → Prompt average: grammar=4.4 creativity=4.5 consistency=6.1 plot=5.2 overall=5.05

Prompt 18/44: 'Anna was a popular girl, who walked to school every day carrying a very heavy backpack. It was so heavy that she could hardly walk.

One day, Anna's friends asked her why her backpack was so heavy. She said that'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=2 creativity=6 consistency=8 plot=5 overall=5.25
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=2.4 creativity=3.4 consistency=4.5 plot=4.8 overall=3.78

Prompt 19/44: 'Once there was a young girl named Anna. She was three years old and usually very happy. Today she was sad because she couldn't play in the park. She had asked her parents to take her but they wouldn't listen. Anna insisted that '
  [1/10] grammar=2 creativity=6 consistency=4 plot=5 overall=4.25
  [2/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [3/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=2 creativity=3 consistency=8 plot=6 overall=4.75
  [7/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [8/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=5.6 creativity=4.8 consistency=6.7 plot=5.3 overall=5.6

Prompt 20/44: 'One day, Grandma was in the kitchen getting ready to prepare. She had the ingredients for a tasty dish.

Grandma said to her granddaughter, "Are you going to help me make this meal?" Her granddaughter, Jenny, replied, "Yes, I will help you!"

Grandma and Jenny began to prepare the ingredients. Jenny was clumsy. She dropped'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=6.2 creativity=4.2 consistency=5.4 plot=3.4 overall=4.8

Prompt 21/44: 'Once upon a time there was a boy named Max. He was at the market with his mother, where he saw two things he wanted very much: a toy car and a jumping rope.

He knew that his mother would not let him buy both of these things, and that she would probably tell him that he has to choose one. He said to her, "I want both'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5

Best model vs Tiny Stories replicated 1 epoch model

In [6]:
import torch
import json
import requests
import yaml
from openai import OpenAI
from transformers import GPT2LMHeadModel, PreTrainedTokenizerFast
from transformers import AutoModelForCausalLM, AutoTokenizer, GPTNeoForCausalLM

# ============ LOAD YOUR MODEL ============
your_model_path = "./runs/finalised_best_model/final_model"
your_model = GPT2LMHeadModel.from_pretrained(your_model_path)
your_tok   = PreTrainedTokenizerFast.from_pretrained(your_model_path)
your_model.eval()
print("Your model loaded ✅")

# ============ LOAD REPLICATED GPT-NEO 33M ============
neo_model_path = "./runs/gptneo_33M_replicated/final_model"
neo_model = GPTNeoForCausalLM.from_pretrained(neo_model_path)
neo_tok   = PreTrainedTokenizerFast.from_pretrained(neo_model_path)
neo_model.eval()
print("Replicated GPT-Neo 33M loaded ✅") 

import ollama  # pip install ollama

# ============ OLLAMA EVAL FUNCTION ============
JUDGE_MODEL = "llama3.1:8b"

def gpt_eval(prompt, story, model_name=JUDGE_MODEL):
    eval_prompt = f"""the following exercise, the student is given a beginning of a story. The student needs to complete it into a full story.
    The exercise tests the student's language abilities and creativity. 
    The symbol *** marks the separator between the prescribed beginning and the student's completion: {prompt}***{story}

    Please provide your general assessment about the part written by the student (the one after the *** symbol). Is it grammatically correct? Is it consistent with the beginning of the story? 
    Pay special attention to whether the student manages to complete the sentence which is split in the middle by the separator ***. 

    Now, grade the student's completion in terms of grammar (1-10), creativity (1-10), consistency (1-10), plot (1-10).

    Return ONLY valid JSON and nothing else — no explanation, no markdown, no backticks:
    {{"grammar": 1, "creativity": 1, "consistency": 1, "plot": 1}}"""

    response = ollama.chat(
        model=model_name,
        messages=[{"role": "user", "content": eval_prompt}],
        format="json",
        options={"temperature": 0.0},
    )

    raw = response["message"]["content"]
    raw = raw.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()

    scores = json.loads(raw)

    for key in ["grammar", "creativity", "consistency", "plot"]:
        scores[key] = max(1, min(10, int(scores[key])))

    scores["overall"] = round(
        (scores["grammar"] + scores["creativity"] + scores["consistency"] + scores["plot"]) / 4, 2
    )
    return scores
    
# ============ FETCH OFFICIAL EVALUATION PROMPTS ============
def fetch_official_prompts():
    url = "https://huggingface.co/datasets/roneneldan/TinyStories/resolve/main/Evaluation%20prompts.yaml"
    try:
        response = requests.get(url)
        response.raise_for_status()
        prompts_data = yaml.safe_load(response.text)

        prompts = []
        for item in prompts_data:
            if isinstance(item, dict):
                prompt = item.get("prompt") or item.get("Prompt") or list(item.values())[0]
                prompts.append(prompt)
            elif isinstance(item, str):
                prompts.append(item)

        print(f"Loaded {len(prompts)} official evaluation prompts ✅")
        return prompts

    except Exception as e:
        print(f"Could not fetch official prompts: {e}")
        print("Falling back to manual prompts...")
        return [
            "Once upon a time there was a little girl",
            "One day a puppy named Max went to the park",
            "The princess lived in a big castle",
            "Tom was very sad because he lost his toy",
            "In the forest there lived a friendly dragon",
        ]

prompts = fetch_official_prompts()
prompts = prompts[:50]
print(f"Using {len(prompts)} prompts for evaluation")

# ============ GENERATION FUNCTION ============
def generate_story(model, tokenizer, prompt, max_new_tokens=200):
    inputs = tokenizer(prompt, return_tensors="pt")
    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=1.0,
            top_p=0.95,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
        )
    full_text = tokenizer.decode(output[0], skip_special_tokens=True)
    generated = full_text[len(prompt):].strip()
    return generated

# ============ EVALUATE ONE MODEL ============
def evaluate_model(model, tokenizer, model_label, prompts, n_completions=10, judge_model="llama3.1:8b"):
    print(f"\n{'='*60}")
    print(f"Evaluating {model_label}...")
    print(f"{'='*60}")

    all_grammar     = []
    all_creativity  = []
    all_consistency = []
    all_plot = []
    all_overall     = []
    results         = []

    for i, prompt in enumerate(prompts):
        print(f"\nPrompt {i+1}/{len(prompts)}: '{prompt}'")

        prompt_grammar     = []
        prompt_creativity  = []
        prompt_consistency = []
        prompt_plot = []
        prompt_stories = []

        for j in range(n_completions):
            story  = generate_story(model, tokenizer, prompt)
            scores = gpt_eval(prompt, story, model_name=judge_model)

            prompt_grammar.append(scores["grammar"])
            prompt_creativity.append(scores["creativity"])
            prompt_consistency.append(scores["consistency"])
            prompt_plot.append(scores["plot"])
            prompt_stories.append(story)

            print(
                f"  [{j+1}/{n_completions}] "
                f"grammar={scores['grammar']} "
                f"creativity={scores['creativity']} "
                f"consistency={scores['consistency']} "
                f"plot={scores['plot']} "
                f"overall={scores['overall']}"
            )

        avg_grammar     = round(sum(prompt_grammar)     / n_completions, 2)
        avg_creativity  = round(sum(prompt_creativity)  / n_completions, 2)
        avg_consistency = round(sum(prompt_consistency) / n_completions, 2)
        avg_plot = round(sum(prompt_plot) / n_completions, 2)
        avg_overall     = round((avg_grammar + avg_creativity + avg_consistency + avg_plot) / 4, 2)

        all_grammar.append(avg_grammar)
        all_creativity.append(avg_creativity)
        all_consistency.append(avg_consistency)
        all_plot.append(avg_plot)
        all_overall.append(avg_overall)

        results.append({
            "prompt"          : prompt,
            "stories"         : prompt_stories,
            "avg_grammar"     : avg_grammar,
            "avg_creativity"  : avg_creativity,
            "avg_consistency" : avg_consistency,
            "avg_plot"        : avg_plot,
            "avg_overall"     : avg_overall,
        })

        print(
            f"  → Prompt average: "
            f"grammar={avg_grammar} "
            f"creativity={avg_creativity} "
            f"consistency={avg_consistency} "
            f"plot={avg_plot} "
            f"overall={avg_overall}"
        )

    final = {
        "model"       : model_label,
        "grammar"     : round(sum(all_grammar)     / len(prompts), 2),
        "creativity"  : round(sum(all_creativity)  / len(prompts), 2),
        "consistency" : round(sum(all_consistency) / len(prompts), 2),
        "plot"        : round(sum(all_plot)        / len(prompts), 2),
        "overall"     : round(sum(all_overall)     / len(prompts), 2),
        "per_prompt"  : results,
    }

    return final

# ============ RUN EVALUATION ============
N_COMPLETIONS = 10
JUDGE_MODEL = "llama3.1:8b"

your_results = evaluate_model(
    your_model, your_tok,
    "Your Model (91.5M GPT-2, ablation params)",
    prompts,
    n_completions=N_COMPLETIONS,
    judge_model=JUDGE_MODEL
)

neo_results = evaluate_model(
    neo_model, neo_tok,
    "Replicated GPT-Neo 33M (standard params, 1 epoch)",
    prompts,
    n_completions=N_COMPLETIONS,
    judge_model=JUDGE_MODEL
)

# ============ SAVE RESULTS ============
all_results = {
    "evaluation_config": {
        "n_prompts"     : len(prompts),
        "n_completions" : N_COMPLETIONS,
        "total_stories" : len(prompts) * N_COMPLETIONS * 2,
        "evaluator"     : JUDGE_MODEL,
        "methodology"   : "LLM-as-a-judge replicating TinyStories GPT-eval framework",
        "comparison"    : "Equal training budget (1 epoch each)"
    },
    "your_model" : your_results,
    "neo_33m"    : neo_results,
}

with open("./gpt_eval_comparison1.json", "w") as f:
    json.dump(all_results, f, indent=2)

print("\nResults saved to gpt_eval_comparison1.json ✅")

# ============ PRINT FINAL COMPARISON ============
print(f"\n{'='*65}")
print("COMPARISON 1 — EQUAL TRAINING BUDGET")
print("Your 91.7M (ablation) vs Replicated GPT-Neo 33M (standard)")
print(f"{len(prompts)} prompts × {N_COMPLETIONS} completions = "
      f"{len(prompts)*N_COMPLETIONS} stories per model")
print(f"{'='*65}")

print(f"\n{'Metric':<15} {'Your 91.7M':>15} {'GPT-Neo 33M':>15} {'Winner':>10}")
print(f"{'─'*57}")

your_wins = 0
neo_wins  = 0

for metric in ["grammar", "creativity", "consistency", "plot", "overall"]:
    your_val = your_results[metric]
    neo_val  = neo_results[metric]

    if your_val >= neo_val:
        winner = "YOURS ✅"
        your_wins += 1
    else:
        winner = "NEO ✅"
        neo_wins += 1

    print(f"{metric:<15} {str(your_val):>15} {str(neo_val):>15} {winner:>10}")

print(f"{'─'*57}")
print(f"{'Total wins':<15} {str(your_wins):>15} {str(neo_wins):>15}")
print(f"\n{'='*65}")
print(f"Context:")
print(f"  Your model:    91.7M params, GPT-2 arch, ablation hyperparams")
print(f"  GPT-Neo 33M:   31.1M params, GPT-Neo arch, standard hyperparams")
print(f"  Both trained:  1 epoch on TinyStories")
print(f"{'='*65}")

Loading weights: 100%|██████████| 148/148 [00:00<00:00, 12252.91it/s]

Your model loaded ✅

Loading weights: 100%|██████████| 56/56 [00:00<00:00, 17228.86it/s]

Replicated GPT-Neo 33M loaded ✅
Loaded 44 official evaluation prompts ✅
Using 44 prompts for evaluation

============================================================
Evaluating Your Model (91.5M GPT-2, ablation params)...
============================================================

Prompt 1/44: 'Once upon a time, there lived a bunny in a field. Her name was Lucy. Lucy loved to have feasts and parties with her bunny friends. One day, when Lucy was about to leave for a feast at a friend's house, she realized she's starting to feel sick. She was so weak she could'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [3/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [6/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=5.0 creativity=3.9 consistency=4.7 plot=3.8 overall=4.35

Prompt 2/44: 'One day a girl walked into the living room and noticed something very strange. There was a huge cabinet standing in the corner. It looked very old and heavy. She walked over and tried to open it, when suddenly'
  [1/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=6 creativity=4 consistency=3 plot=5 overall=4.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=5.4 creativity=4.0 consistency=4.8 plot=3.9 overall=4.52

Prompt 3/44: 'Once upon a time, there lived a hamster in the forest. Every day, he would walked around the forest and looking for adventures. One day, he heard someone calling out from behind the bushes.

The hamster listened carefully. He realised that it was a small mouse calling out for help. It got stuck under a heavy log and couldn't get out. The hamster immediately realized that'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=4 creativity=2 consistency=3 plot=5 overall=3.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  → Prompt average: grammar=5.4 creativity=4.0 consistency=5.4 plot=4.4 overall=4.8

Prompt 4/44: 'Jack asked his mom if he could ride the bike all the way to his grandmother's house. She agreed, but she said that he shouldn't ride too fast because it was raining and the path was wet.

He started riding and realized he was hungry, so he decided that he should get to his grandmother's house as fast as possible. But then he remembered his mum's words "'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=2 creativity=6 consistency=8 plot=4 overall=5.0
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=2 creativity=6 consistency=8 plot=4 overall=5.0
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=3.4 creativity=4.1 consistency=5.5 plot=4.6 overall=4.4

Prompt 5/44: 'Alice was bored and wanted to find some adventures. She walked up to her friend Ben, who looked vey busy playing with his toys. Alice said, "Why don't we'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=6 creativity=4 consistency=3 plot=5 overall=4.5
  [5/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [9/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=5.0 creativity=3.9 consistency=4.5 plot=4.0 overall=4.35

Prompt 6/44: 'Alice walked up to her friend Ben's house. She was planning to ask him to go to the park with her. When Ben opened the door, she asked him if he had any plans. He said, "I'm sorry, Alice, but'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=8 creativity=6 consistency=9 plot=5 overall=7.0
  [5/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [6/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=4 creativity=6 consistency=3 plot=5 overall=4.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=2 creativity=6 consistency=8 plot=9 overall=6.25
  → Prompt average: grammar=3.2 creativity=4.6 consistency=5.7 plot=5.6 overall=4.78

Prompt 7/44: 'The day before Ben's birthday, Alice walked into the kitchen and saw Ben sitting there, looking Gloomy. She said, "Ben, why are you'
  [1/10] grammar=6 creativity=4 consistency=8 plot=5 overall=5.75
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=4 creativity=2 consistency=3 plot=5 overall=3.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=3.8 creativity=3.3 consistency=4.6 plot=4.4 overall=4.03

Prompt 8/44: 'Alice walked into the kitchen and saw Ben who was looking for something but looked frustrated. She said, "Ben, why are you'
  [1/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [2/10] grammar=8 creativity=2 consistency=6 plot=3 overall=4.75
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=4.8 creativity=3.6 consistency=5.1 plot=4.2 overall=4.42

Prompt 9/44: 'Once upon a time there was a curious boy who lived in a house with a big garden. Every day he explored the garden he found new surprises. But one day, it was raining so hard that his mother told him'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=4 creativity=6 consistency=5 plot=7 overall=5.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=4.4 creativity=4.0 consistency=5.0 plot=4.6 overall=4.5

Prompt 10/44: 'Once upon a time, there was tiger who liked to play the guitar. One day, a bunny heard the guitar from a distance and'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [3/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=5.8 creativity=4.4 consistency=5.5 plot=3.7 overall=4.85

Prompt 11/44: 'Alice wanted to play with her doll, but she couldn't remember where she had put it. She looked all around the house but couldn't find it, so she decided'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [3/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [4/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [5/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=8 creativity=6 consistency=9 plot=5 overall=7.0
  → Prompt average: grammar=6.2 creativity=4.8 consistency=6.8 plot=5.2 overall=5.75

Prompt 12/44: '"Ben, what do you have in your pocket?", Alice asked. "Oh, nothing.", Ben replied. But Alice saw that there was definitely something in Ben's pocket, and she was very curious what it was, so she'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=2.8 creativity=3.2 consistency=4.2 plot=4.6 overall=3.7

Prompt 13/44: 'One day, a bird was flying high over the sea. At some point the bird noticed small boat with a boy sitting inside. The boy looked lost so'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [9/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [10/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  → Prompt average: grammar=4.8 creativity=4.3 consistency=5.6 plot=4.7 overall=4.85

Prompt 14/44: 'Jimmy was on his way to school with his father when he noticed a tree with strange looking fruits on it. He asked his father, "Can I try'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [3/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=3.6 creativity=3.7 consistency=5.1 plot=5.2 overall=4.4

Prompt 15/44: 'Once upon a time, there lived two best friends called Jack and Joe. They were bored, they wanted someone else to talk to or play with. Jack had an idea. He said to Joe, “Let’s go and find'
  [1/10] grammar=6 creativity=4 consistency=8 plot=5 overall=5.75
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [4/10] grammar=4 creativity=6 consistency=8 plot=5 overall=5.75
  [5/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [6/10] grammar=2 creativity=3 consistency=8 plot=6 overall=4.75
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=4.8 creativity=4.1 consistency=5.9 plot=4.4 overall=4.8

Prompt 16/44: 'Jack and Sally were running through the woods together when they stopped suddenly. They heard a strange sound coming from around the corner.

“What's that?” asked Jack.

Sally put her finger to her lips and said, “Shhhh. Let's go find out.”

Jack and Sally followed the'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=4 creativity=6 consistency=3 plot=5 overall=4.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  → Prompt average: grammar=2.6 creativity=3.4 consistency=3.8 plot=4.7 overall=3.62

Prompt 17/44: 'Once upon a time there was a little bear named Diva. She was hungry, and wanted to bake a cake, but she didn't have any sugar at home, so she decided to go ask around. She started walking and met a squirrel. She asked the squirrel, "Would you happen'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [3/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=6 creativity=4 consistency=8 plot=5 overall=5.75
  [7/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [8/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=5.8 creativity=4.7 consistency=6.7 plot=5.0 overall=5.55

Prompt 18/44: 'Anna was a popular girl, who walked to school every day carrying a very heavy backpack. It was so heavy that she could hardly walk.

One day, Anna's friends asked her why her backpack was so heavy. She said that'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=2 creativity=6 consistency=4 plot=5 overall=4.25
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=2.0 creativity=3.3 consistency=4.0 plot=5.0 overall=3.58

Prompt 19/44: 'Once there was a young girl named Anna. She was three years old and usually very happy. Today she was sad because she couldn't play in the park. She had asked her parents to take her but they wouldn't listen. Anna insisted that '
  [1/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [7/10] grammar=8 creativity=2 consistency=6 plot=4 overall=5.0
  [8/10] grammar=2 creativity=6 consistency=4 plot=5 overall=4.25
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  → Prompt average: grammar=4.8 creativity=4.2 consistency=5.8 plot=5.3 overall=5.03

Prompt 20/44: 'One day, Grandma was in the kitchen getting ready to prepare. She had the ingredients for a tasty dish.

Grandma said to her granddaughter, "Are you going to help me make this meal?" Her granddaughter, Jenny, replied, "Yes, I will help you!"

Grandma and Jenny began to prepare the ingredients. Jenny was clumsy. She dropped'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [10/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  → Prompt average: grammar=5.8 creativity=4.1 consistency=5.1 plot=3.5 overall=4.62

Prompt 21/44: 'Once upon a time there was a boy named Max. He was at the market with his mother, where he saw two things he wanted very much: a toy car and a jumping rope.

He knew that his mother would not let him buy both of these things, and that she would probably tell him that he has to choose one. He said to her, "I want both'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5

Best model vs 20B Model

In [7]:
import torch
import json
import requests
import yaml
from openai import OpenAI
from transformers import GPT2LMHeadModel, PreTrainedTokenizerFast
from transformers import AutoModelForCausalLM, AutoTokenizer

# ============ LOAD YOUR MODEL ============
your_model_path = "./runs/finalised_best_model/final_model"
your_model = GPT2LMHeadModel.from_pretrained(your_model_path)
your_tok   = PreTrainedTokenizerFast.from_pretrained(your_model_path)
your_model.eval()
print("Your model loaded ✅")

# ============ LOAD 1T MODEL ============
vl_model = AutoModelForCausalLM.from_pretrained("EleutherAI/gpt-neox-20b")  # Replace with the appropriate model
vl_tok   = AutoTokenizer.from_pretrained("EleutherAI/gpt-neox-20b")        # Replace with the tokenizer for the larger model
vl_tok.pad_token = vl_tok.eos_token
vl_model.eval()
print("20B Model Loaded loaded ✅")

import ollama  # pip install ollama

# ============ OLLAMA EVAL FUNCTION ============
JUDGE_MODEL = "llama3.1:8b"

def gpt_eval(prompt, story, model_name=JUDGE_MODEL):
    eval_prompt = f"""the following exercise, the student is given a beginning of a story. The student needs to complete it into a full story.
    The exercise tests the student's language abilities and creativity. 
    The symbol *** marks the separator between the prescribed beginning and the student's completion: {prompt}***{story}

    Please provide your general assessment about the part written by the student (the one after the *** symbol). Is it grammatically correct? Is it consistent with the beginning of the story? 
    Pay special attention to whether the student manages to complete the sentence which is split in the middle by the separator ***. 

    Now, grade the student's completion in terms of grammar (1-10), creativity (1-10), consistency (1-10), plot (1-10).

    Return ONLY valid JSON and nothing else — no explanation, no markdown, no backticks:
    {{"grammar": 1, "creativity": 1, "consistency": 1, "plot": 1}}"""

    response = ollama.chat(
        model=model_name,
        messages=[{"role": "user", "content": eval_prompt}],
        format="json",
        options={"temperature": 0.0},
    )

    raw = response["message"]["content"]
    raw = raw.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()

    scores = json.loads(raw)

    for key in ["grammar", "creativity", "consistency", "plot"]:
        scores[key] = max(1, min(10, int(scores[key])))

    scores["overall"] = round(
        (scores["grammar"] + scores["creativity"] + scores["consistency"] + scores["plot"]) / 4, 2
    )
    return scores
    
# ============ FETCH OFFICIAL EVALUATION PROMPTS ============
def fetch_official_prompts():
    url = "https://huggingface.co/datasets/roneneldan/TinyStories/resolve/main/Evaluation%20prompts.yaml"
    try:
        response = requests.get(url)
        response.raise_for_status()
        prompts_data = yaml.safe_load(response.text)

        prompts = []
        for item in prompts_data:
            if isinstance(item, dict):
                prompt = item.get("prompt") or item.get("Prompt") or list(item.values())[0]
                prompts.append(prompt)
            elif isinstance(item, str):
                prompts.append(item)

        print(f"Loaded {len(prompts)} official evaluation prompts ✅")
        return prompts

    except Exception as e:
        print(f"Could not fetch official prompts: {e}")
        print("Falling back to manual prompts...")
        return [
            "Once upon a time there was a little girl",
            "One day a puppy named Max went to the park",
            "The princess lived in a big castle",
            "Tom was very sad because he lost his toy",
            "In the forest there lived a friendly dragon",
        ]

prompts = fetch_official_prompts()
prompts = prompts[:50]
print(f"Using {len(prompts)} prompts for evaluation")

# ============ GENERATION FUNCTION ============
def generate_story(model, tokenizer, prompt, max_new_tokens=200):
    inputs = tokenizer(prompt, return_tensors="pt")
    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=1.0,
            top_p=0.95,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
        )
    full_text = tokenizer.decode(output[0], skip_special_tokens=True)
    generated = full_text[len(prompt):].strip()
    return generated

# ============ EVALUATE ONE MODEL ============
def evaluate_model(model, tokenizer, model_label, prompts, n_completions=10, judge_model="llama3.1:8b"):
    print(f"\n{'='*60}")
    print(f"Evaluating {model_label}...")
    print(f"{'='*60}")

    all_grammar     = []
    all_creativity  = []
    all_consistency = []
    all_plot = []
    all_overall     = []
    results         = []

    for i, prompt in enumerate(prompts):
        print(f"\nPrompt {i+1}/{len(prompts)}: '{prompt}'")

        prompt_grammar     = []
        prompt_creativity  = []
        prompt_consistency = []
        prompt_plot = []
        prompt_stories = []

        for j in range(n_completions):
            story  = generate_story(model, tokenizer, prompt)
            scores = gpt_eval(prompt, story, model_name=judge_model)

            prompt_grammar.append(scores["grammar"])
            prompt_creativity.append(scores["creativity"])
            prompt_consistency.append(scores["consistency"])
            prompt_plot.append(scores["plot"])
            prompt_stories.append(story)

            print(
                f"  [{j+1}/{n_completions}] "
                f"grammar={scores['grammar']} "
                f"creativity={scores['creativity']} "
                f"consistency={scores['consistency']} "
                f"plot={scores['plot']} "
                f"overall={scores['overall']}"
            )

        avg_grammar     = round(sum(prompt_grammar)     / n_completions, 2)
        avg_creativity  = round(sum(prompt_creativity)  / n_completions, 2)
        avg_consistency = round(sum(prompt_consistency) / n_completions, 2)
        avg_plot = round(sum(prompt_plot) / n_completions, 2)
        avg_overall     = round((avg_grammar + avg_creativity + avg_consistency + avg_plot) / 4, 2)

        all_grammar.append(avg_grammar)
        all_creativity.append(avg_creativity)
        all_consistency.append(avg_consistency)
        all_plot.append(avg_plot)
        all_overall.append(avg_overall)

        results.append({
            "prompt"          : prompt,
            "stories"         : prompt_stories,
            "avg_grammar"     : avg_grammar,
            "avg_creativity"  : avg_creativity,
            "avg_consistency" : avg_consistency,
            "avg_plot"        : avg_plot,
            "avg_overall"     : avg_overall,
        })

        print(
            f"  → Prompt average: "
            f"grammar={avg_grammar} "
            f"creativity={avg_creativity} "
            f"consistency={avg_consistency} "
            f"plot={avg_plot} "
            f"overall={avg_overall}"
        )

    final = {
        "model"       : model_label,
        "grammar"     : round(sum(all_grammar)     / len(prompts), 2),
        "creativity"  : round(sum(all_creativity)  / len(prompts), 2),
        "consistency" : round(sum(all_consistency) / len(prompts), 2),
        "plot"        : round(sum(all_plot)        / len(prompts), 2),
        "overall"     : round(sum(all_overall)     / len(prompts), 2),
        "per_prompt"  : results,
    }

    return final

# ============ RUN EVALUATION ============
N_COMPLETIONS = 10
JUDGE_MODEL = "llama3.1:8b"

your_results = evaluate_model(
    your_model, your_tok,
    "Your Model (91.5M GPT-2, ablation params)",
    prompts,
    n_completions=N_COMPLETIONS,
    judge_model=JUDGE_MODEL
)

neo_results = evaluate_model(
    vl_model, vl_tok,
    "20B (Open Source Model)",
    prompts,
    n_completions=N_COMPLETIONS,
    judge_model=JUDGE_MODEL
)

# ============ SAVE RESULTS ============
all_results = {
    "evaluation_config": {
        "n_prompts"     : len(prompts),
        "n_completions" : N_COMPLETIONS,
        "total_stories" : len(prompts) * N_COMPLETIONS * 2,
        "evaluator"     : JUDGE_MODEL,
        "methodology"   : "LLM-as-a-judge replicating TinyStories GPT-eval framework",
        "comparison"    : "Equal training budget (1 epoch each)"
    },
    "your_model" : your_results,
    "1t_model"    : neo_results,
}

with open("./gpt_eval_comparison1.json", "w") as f:
    json.dump(all_results, f, indent=2)

print("\nResults saved to gpt_eval_comparison1.json ✅")

# ============ PRINT FINAL COMPARISON ============
print(f"\n{'='*65}")
print("COMPARISON 1 — EQUAL TRAINING BUDGET")
print("Your 91.7M (ablation) vs 20B (Open Source)")
print(f"{len(prompts)} prompts × {N_COMPLETIONS} completions = "
      f"{len(prompts)*N_COMPLETIONS} stories per model")
print(f"{'='*65}")

print(f"\n{'Metric':<15} {'Your 91.7M':>15} {'20B':>15} {'Winner':>10}")
print(f"{'─'*57}")

your_wins = 0
neo_wins  = 0

for metric in ["grammar", "creativity", "consistency", "plot", "overall"]:
    your_val = your_results[metric]
    neo_val  = neo_results[metric]

    if your_val >= neo_val:
        winner = "YOURS ✅"
        your_wins += 1
    else:
        winner = "20B ✅"
        neo_wins += 1

    print(f"{metric:<15} {str(your_val):>15} {str(neo_val):>15} {winner:>10}")

print(f"{'─'*57}")
print(f"{'Total wins':<15} {str(your_wins):>15} {str(neo_wins):>15}")
print(f"\n{'='*65}")
print(f"Context:")
print(f"  Your model:    91.7M params, GPT-2 arch, ablation hyperparams")
print(f"  20B model:   20B params, GPT-Neox arch, standard hyperparams")
print(f"  Both trained:  1 epoch on TinyStories")
print(f"{'='*65}")

Loading weights: 100%|██████████| 148/148 [00:00<00:00, 1915.72it/s]
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Your model loaded ✅

Loading weights: 100%|██████████| 532/532 [00:00<00:00, 1318.68it/s]

20B Model Loaded loaded ✅
Loaded 44 official evaluation prompts ✅
Using 44 prompts for evaluation

============================================================
Evaluating Your Model (91.5M GPT-2, ablation params)...
============================================================

Prompt 1/44: 'Once upon a time, there lived a bunny in a field. Her name was Lucy. Lucy loved to have feasts and parties with her bunny friends. One day, when Lucy was about to leave for a feast at a friend's house, she realized she's starting to feel sick. She was so weak she could'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=5.6 creativity=3.9 consistency=4.5 plot=3.0 overall=4.25

Prompt 2/44: 'One day a girl walked into the living room and noticed something very strange. There was a huge cabinet standing in the corner. It looked very old and heavy. She walked over and tried to open it, when suddenly'
  [1/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=2 creativity=6 consistency=8 plot=9 overall=6.25
  [5/10] grammar=6 creativity=4 consistency=8 plot=5 overall=5.75
  [6/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=4.4 creativity=4.2 consistency=6.0 plot=5.4 overall=5.0

Prompt 3/44: 'Once upon a time, there lived a hamster in the forest. Every day, he would walked around the forest and looking for adventures. One day, he heard someone calling out from behind the bushes.

The hamster listened carefully. He realised that it was a small mouse calling out for help. It got stuck under a heavy log and couldn't get out. The hamster immediately realized that'
  [1/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=4 creativity=6 consistency=5 plot=7 overall=5.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=4.8 creativity=4.1 consistency=5.1 plot=4.4 overall=4.6

Prompt 4/44: 'Jack asked his mom if he could ride the bike all the way to his grandmother's house. She agreed, but she said that he shouldn't ride too fast because it was raining and the path was wet.

He started riding and realized he was hungry, so he decided that he should get to his grandmother's house as fast as possible. But then he remembered his mum's words "'
  [1/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [2/10] grammar=2 creativity=6 consistency=4 plot=5 overall=4.25
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=2 creativity=6 consistency=4 plot=5 overall=4.25
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [7/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [10/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  → Prompt average: grammar=3.2 creativity=4.8 consistency=5.1 plot=4.8 overall=4.47

Prompt 5/44: 'Alice was bored and wanted to find some adventures. She walked up to her friend Ben, who looked vey busy playing with his toys. Alice said, "Why don't we'
  [1/10] grammar=6 creativity=4 consistency=7 plot=5 overall=5.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=2 creativity=6 consistency=8 plot=9 overall=6.25
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=5.2 creativity=4.4 consistency=6.1 plot=5.0 overall=5.18

Prompt 6/44: 'Alice walked up to her friend Ben's house. She was planning to ask him to go to the park with her. When Ben opened the door, she asked him if he had any plans. He said, "I'm sorry, Alice, but'
  [1/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [2/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=3.2 creativity=3.6 consistency=5.0 plot=5.4 overall=4.3

Prompt 7/44: 'The day before Ben's birthday, Alice walked into the kitchen and saw Ben sitting there, looking Gloomy. She said, "Ben, why are you'
  [1/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [2/10] grammar=2 creativity=6 consistency=4 plot=5 overall=4.25
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=4.8 creativity=4.3 consistency=5.2 plot=4.5 overall=4.7

Prompt 8/44: 'Alice walked into the kitchen and saw Ben who was looking for something but looked frustrated. She said, "Ben, why are you'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=2 creativity=4 consistency=3 plot=5 overall=3.5
  [3/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [4/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=4.4 creativity=4.3 consistency=5.4 plot=4.9 overall=4.75

Prompt 9/44: 'Once upon a time there was a curious boy who lived in a house with a big garden. Every day he explored the garden he found new surprises. But one day, it was raining so hard that his mother told him'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=6 creativity=4 consistency=7 plot=5 overall=5.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=4 creativity=6 consistency=8 plot=7 overall=6.25
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=5.8 creativity=4.5 consistency=6.2 plot=4.6 overall=5.28

Prompt 10/44: 'Once upon a time, there was tiger who liked to play the guitar. One day, a bunny heard the guitar from a distance and'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [3/10] grammar=6 creativity=4 consistency=3 plot=5 overall=4.5
  [4/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [5/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [6/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  → Prompt average: grammar=6.8 creativity=4.8 consistency=6.2 plot=4.7 overall=5.62

Prompt 11/44: 'Alice wanted to play with her doll, but she couldn't remember where she had put it. She looked all around the house but couldn't find it, so she decided'
  [1/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=6.4 creativity=4.4 consistency=5.8 plot=3.8 overall=5.1

Prompt 12/44: '"Ben, what do you have in your pocket?", Alice asked. "Oh, nothing.", Ben replied. But Alice saw that there was definitely something in Ben's pocket, and she was very curious what it was, so she'
  [1/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [2/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [3/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=4 creativity=6 consistency=8 plot=7 overall=6.25
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [10/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  → Prompt average: grammar=5.2 creativity=4.5 consistency=6.2 plot=5.2 overall=5.27

Prompt 13/44: 'One day, a bird was flying high over the sea. At some point the bird noticed small boat with a boy sitting inside. The boy looked lost so'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [4/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [7/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=4.6 creativity=4.4 consistency=5.9 plot=5.3 overall=5.05

Prompt 14/44: 'Jimmy was on his way to school with his father when he noticed a tree with strange looking fruits on it. He asked his father, "Can I try'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=8 creativity=6 consistency=9 plot=5 overall=7.0
  [3/10] grammar=8 creativity=2 consistency=6 plot=4 overall=5.0
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=4.2 creativity=3.6 consistency=5.3 plot=4.9 overall=4.5

Prompt 15/44: 'Once upon a time, there lived two best friends called Jack and Joe. They were bored, they wanted someone else to talk to or play with. Jack had an idea. He said to Joe, “Let’s go and find'
  [1/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [2/10] grammar=2 creativity=3 consistency=8 plot=6 overall=4.75
  [3/10] grammar=6 creativity=4 consistency=8 plot=5 overall=5.75
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=6 creativity=4 consistency=3 plot=2 overall=3.75
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=2 creativity=6 consistency=8 plot=5 overall=5.25
  → Prompt average: grammar=4.6 creativity=4.4 consistency=6.3 plot=4.6 overall=4.97

Prompt 16/44: 'Jack and Sally were running through the woods together when they stopped suddenly. They heard a strange sound coming from around the corner.

“What's that?” asked Jack.

Sally put her finger to her lips and said, “Shhhh. Let's go find out.”

Jack and Sally followed the'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [3/10] grammar=4 creativity=6 consistency=5 plot=7 overall=5.5
  [4/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [8/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=2.2 creativity=3.3 consistency=4.1 plot=5.2 overall=3.7

Prompt 17/44: 'Once upon a time there was a little bear named Diva. She was hungry, and wanted to bake a cake, but she didn't have any sugar at home, so she decided to go ask around. She started walking and met a squirrel. She asked the squirrel, "Would you happen'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [3/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [4/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [7/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [10/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  → Prompt average: grammar=5.0 creativity=5.1 consistency=7.0 plot=5.6 overall=5.68

Prompt 18/44: 'Anna was a popular girl, who walked to school every day carrying a very heavy backpack. It was so heavy that she could hardly walk.

One day, Anna's friends asked her why her backpack was so heavy. She said that'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [5/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [6/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [7/10] grammar=4 creativity=6 consistency=8 plot=7 overall=6.25
  [8/10] grammar=2 creativity=6 consistency=8 plot=7 overall=5.75
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=2.6 creativity=4.0 consistency=5.3 plot=5.4 overall=4.32

Prompt 19/44: 'Once there was a young girl named Anna. She was three years old and usually very happy. Today she was sad because she couldn't play in the park. She had asked her parents to take her but they wouldn't listen. Anna insisted that '
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [2/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [3/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=6 creativity=4 consistency=7 plot=5 overall=5.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [8/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [9/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [10/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  → Prompt average: grammar=5.4 creativity=4.3 consistency=6.1 plot=5.0 overall=5.2

Prompt 20/44: 'One day, Grandma was in the kitchen getting ready to prepare. She had the ingredients for a tasty dish.

Grandma said to her granddaughter, "Are you going to help me make this meal?" Her granddaughter, Jenny, replied, "Yes, I will help you!"

Grandma and Jenny began to prepare the ingredients. Jenny was clumsy. She dropped'
  [1/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [2/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [3/10] grammar=8 creativity=6 consistency=9 plot=7 overall=7.5
  [4/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [5/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  [6/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [7/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [8/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [9/10] grammar=6 creativity=4 consistency=5 plot=3 overall=4.5
  [10/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5
  → Prompt average: grammar=5.8 creativity=4.4 consistency=6.0 plot=4.6 overall=5.2

Prompt 21/44: 'Once upon a time there was a boy named Max. He was at the market with his mother, where he saw two things he wanted very much: a toy car and a jumping rope.

He knew that his mother would not let him buy both of these things, and that she would probably tell him that he has to choose one. He said to her, "I want both'
  [1/10] grammar=2 creativity=3 consistency=4 plot=5 overall=3.5